upstream backend_upstream {
  server ${BACKEND_HOST}:${BACKEND_PORT};
}

server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;
  location /api/ { proxy_pass http://backend_upstream; proxy_set_header Host $host; }
  location /health { proxy_pass http://backend_upstream; }
  location /metrics { proxy_pass http://backend_upstream; }
}